### ISSUE TITLE
option to set amount of numbers/special characters etc.

### ISSUE THREAD

**Issue by akorinek** [hackzilla/password-generator#18]
My password validation needs passwords which contain at least two numbers in the password. 
I'm using this code:

 $generator = new ComputerPasswordGenerator();
        $generator
            ->setOptionValue(ComputerPasswordGenerator::OPTION_UPPER_CASE, true)
            ->setOptionValue(ComputerPasswordGenerator::OPTION_LOWER_CASE, true)
            ->setOptionValue(ComputerPasswordGenerator::OPTION_NUMBERS, true)
            ->setOptionValue(ComputerPasswordGenerator::OPTION_SYMBOLS, true)
            ->setLength(12);
        $password = $generator->generatePassword();

Sometimes I get passwords with only one number. Is there an option to define how many of each character classes will be in the password?

**Comment by hackzilla** [comment]
Thats a very good issue.

I can imagine this would be handy for a few people.

**Comment by hackzilla** [comment]
I've added a class called RequirementPasswordGenerator (which extends ComputerPasswordGenerator).
It is currently in develop branch, as I'm still trying to figure out ```validLimits()``` if the set of options will result in an infinite loop.  Though I might have to drop that in favour of different method.

The idea is that it will work like this:

```
$generator = new RequirementPasswordGenerator();
$generator
            ->setOptionValue(RequirementPasswordGenerator::OPTION_UPPER_CASE, true)
            ->setOptionValue(RequirementPasswordGenerator::OPTION_LOWER_CASE, true)
            ->setOptionValue(RequirementPasswordGenerator::OPTION_NUMBERS, true)
            ->setOptionValue(RequirementPasswordGenerator::OPTION_SYMBOLS, true)
            ->setLength(12);
            ->setMinimumCount(RequirementPasswordGenerator::OPTION_SYMBOLS, 2)
            ->setMaximumCount(RequirementPasswordGenerator::OPTION_SYMBOLS, 4)
```

Let me know what you think.

**Comment by akorinek** [comment]
That looks great, would do exactly what I would need. This would need to check that there is no overcommitting though, so for example for a length 12 the sum of all the minimums cannot be more than 12, and the maximum less than 12.

**Comment by hackzilla** [comment]
I believe I've got checks right for over committing.
This has now been put in master at version 1.3.0.

Let me know if you encounter any issues with it.
