### ISSUE TITLE
Specify character list

### ISSUE THREAD

**Issue by poxin13** [hackzilla/password-generator#21]
I have a specific requirement where in I can only use certain special characters. Is there anyway to specify what ones will be used when generating a password?

Another odd requirement is my first character must be alphanumeric, but I can do this after with substr.

**Comment by hackzilla** [comment]
There is one main way to do it.
I'm assuming that we are talking about the ComputerPasswordGenerator

https://github.com/hackzilla/password-generator/blob/master/Generator/ComputerPasswordGenerator.php#L26

```
  $generator = (new ComputerPasswordGenerator())->setParameter(self::PARAMETER_UPPER_CASE, 'AZ')
```

or you can extend ComputerPasswordGenerator and override the constructor with your own config.

**Comment by poxin13** [comment]
Apologies, should have specified I'm using the RequirementPasswordGenerator. It's come in pretty handy as applications we use have very specific password requirements.

**Comment by hackzilla** [comment]
It'll be the same with RequirementPasswordGenerator, as that extends ComputerPasswordGenerator anyway.

If you override the contractor you will need to call the parent.

```
class MyPasswordGenerator extends RequirementPasswordGenerator
{
    /**
     */
    public function __construct()
    {
        parent::__construct();
        $this
            ->setParameter(self::PARAMETER_UPPER_CASE, 'AZ')
            ->setParameter(self::PARAMETER_LOWER_CASE, 'az')
            ->setParameter(self::PARAMETER_NUMBERS, '0123789')
            ->setParameter(self::PARAMETER_SYMBOLS, '!@+')
    }
}
```

**Comment by poxin13** [comment]
Using setParameter worked fine, thanks!
