### ISSUE TITLE
Must include

### ISSUE THREAD

**Issue by TwinMist** [hackzilla/password-generator#30]
Hi
I there anyway that you can set that is  MUST include one for each of the following

  ->setUppercase(true)
  ->setLowercase(true)
  ->setNumbers(true)
  ->setSymbols(false)

**Comment by hackzilla** [comment]
Sorry about the delay.

There is a RequirementPasswordGenerator that works like that.

**Comment by TwinMist** [comment]
Thanks, didn't see that
