### ISSUE TITLE
In some test detect that package with correct call, not generate password correct

### ISSUE THREAD

**Issue by abkrim** [hackzilla/password-generator#37]
```php
use Hackzilla\PasswordGenerator\Generator\ComputerPasswordGenerator;

$generator = new ComputerPasswordGenerator();
$generator->setUppercase(true)->setLowercase(true)->setNumbers(true)->setSymbols(true)->setLength(12)

$password = $generator->generatePasswords(10);
=> [
     "Qk-K4%*n,]%w",
     "kQ7Tzu@AnX9g",
     "%r{?)e5x64$^", // Wrong. Not uppercase
     ")KeT(YkW4q)S",
     "LD5KRnbQ9e/2",
     "Y7Ej{%.D>mv}",
     "e6}f2ERf>eCn",
     "L6!%e<!QSy,2",
     "V[_B@bw4yj/W",
     "M=LJajjm]C!=",
   ]

```

The problem skipped me when, when using the package in my tests, the validation of the passwords in the generation of password for the creation of users failed me.

**Comment by hackzilla** [comment]
The `ComputerPasswordGenerator` has not checks that make sure the password conforms to the options. 
The `RequirementPasswordGenerator` is what you need.

**Comment by abkrim** [comment]
Hi. Yes, I see yestarday. Now using RequirementPasswordGenerator, and make some tests and it's work fine. Best regards.
