### ISSUE TITLE
not found after following instructions

### ISSUE THREAD

**Issue by sk8ermeb** [hackzilla/password-generator#38]
I followed the instruction on the home screen and I am getting the following error
PHP Fatal error:  Uncaught Error: Class "Hackzilla\PasswordGenerator\Generator\ComputerPasswordGenerator" not found in  /myphpfil..."

I am using php8 and ubuntu 22, so maybe this hasn't been tested on the latest php version?

**Comment by hackzilla** [comment]
Hi @sk8ermeb 

I made an assumption in the readme, that you'd be using an autoloader.
I'll update the instructions.

To get you going this is the full example:

```
<?php

require 'vendor/autoload.php';

use Hackzilla\PasswordGenerator\Generator\ComputerPasswordGenerator;

$generator = new ComputerPasswordGenerator();

$generator
  ->setOptionValue(ComputerPasswordGenerator::OPTION_UPPER_CASE, true)
  ->setOptionValue(ComputerPasswordGenerator::OPTION_LOWER_CASE, true)
  ->setOptionValue(ComputerPasswordGenerator::OPTION_NUMBERS, true)
  ->setOptionValue(ComputerPasswordGenerator::OPTION_SYMBOLS, false)
;

$password = $generator->generatePassword();
echo $password . PHP_EOL;
```

Hopefully this solves you issue.
