### ISSUE TITLE
Facebook 

### ISSUE THREAD

**Issue by jamiegreen7** [hackzilla/password-generator#39]
Hack https://www.facebook.com/cristiandavid.caicedonazareno?mibextid=LQQJ4d

**Comment by jamiegreen7** [comment]
> Hack https://www.facebook.com/cristiandavid.caicedonazareno?mibextid=LQQJ4d

**Comment by hackzilla** [comment]
?

**Comment by nyhtml** [comment]
A shameful plug would be my guess. 😂
